name: Legacy CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node and Install Dependencies
        uses: ./.github/actions/setup-node-deps
        with:
          node_version: '20'
          cache_path: |
            node_modules
            ~/.npm

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build static files
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
