name: Self-Hosted CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: linux-vm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build static files
        run: npm run build
