name: Service Containers Practice

on:
  push:
  workflow_dispatch:

jobs:
  test-services:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    services:
      nginx:
        image: nginx:alpine
        ports:
          - 80

      apache:
        image: httpd:2.4
        ports:
          - 80

    steps:
      - name: Install curl
        run: apk add --no-cache curl

      - name: Check NGINX Service
        run: |
          curl -f http://nginx || exit 1
          echo "NGINX is running"

      - name: Check Apache Service
        run: |
          curl -f http://apache || exit 1
          echo "Apache is running"
